component: http
name: http-express-MCvgX54Rax
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    framework: express
    name: '${name}'
    runtime: Nodejs12.16
    eip: false
    timeout: 3
    memorySize: 256
    tags: []
    environments: []
    layers:
      - name: '${output:${stage}:${app}:api-layer.name}'
        version: '${output:${stage}:${app}:api-layer.version}'
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains:
      - domain: api.imissyou.today
        certId: xNYiMDMr
        protocols:
          - http
          - https
        pathMap:
          - path: /
            environment: release
        customMap: true
        isDefaultMapping: false
  region: ap-guangzhou
  isAutoCiDeploy: false
org: '1253108538'
app: api
stage: dev
